// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import '/models/cart_item_model.dart';
import '/models/provider_model.dart';
import '/models/service_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(ProviderModelAdapter());
    registerAdapter(ServiceModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(ProviderModelAdapter());
    registerAdapter(ServiceModelAdapter());
  }
}
